[tool.coverage.run]
branch = true
source = [ "bsb_neuron" ]

[tool.coverage.report]
exclude_lines = [ "if TYPE_CHECKING:" ]
show_missing = true

[tool.pytest.ini_options]
addopts = """
 --cov
 --cov-report html:'../../coverage/packages/bsb-neuron/html'
 --cov-report xml:'../../coverage/packages/bsb-neuron/coverage.xml'
 --html='../../reports/packages/bsb-neuron/unittests/html/index.html'
 --junitxml='../../reports/packages/bsb-neuron/unittests/junit.xml'
"""

[tool.ruff]
exclude = [ ".ruff_cache", ".svn", ".tox", ".venv", "dist" ]
line-length = 88
indent-width = 4

  [tool.ruff.lint]
  select = [ "E", "F", "UP", "B", "SIM", "I" ]
  ignore = [ ]
  fixable = [ "ALL" ]
  unfixable = [ ]

[tool.uv.sources.bsb-core]
path = "../bsb-core"
editable = true

[project]
name = "bsb-neuron"
version = "6.0.0-a2"
readme = "README.md"
classifiers = [
  "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)"
]
dynamic = [ "description" ]
requires-python = ">=3.10"
dependencies = [
  "bsb-core~=6.0",
  "nrn-patch~=4.0; sys_platform != 'win32'",
  "arborize[neuron]~=4.1; sys_platform != 'win32'"
]

  [[project.authors]]
  name = "Robin De Schepper"
  email = "robin@alexandria.sc"

  [[project.authors]]
  name = "Dimitri Rodarie"
  email = "dimitri.rodarie@unipv.it"

  [project.license]
  file = "LICENSE"

[dependency-groups]
dev = [
  "autopep8>=2.3.1",
  "ruff>=0.8.2",
  "pytest>=8.3.4",
  "pytest-sugar>=1.0.0",
  "pytest-cov>=6.0.0",
  "pytest-html>=4.1.1"
]

[build-system]
requires = [ "flit_core >=3.2,<4" ]
build-backend = "flit_core.buildapi"
