version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.11"
    nodejs: "22"
  apt_packages:
    - libopenmpi-dev
    - openmpi-bin
  jobs:
    create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
    install:
      - "true"
    pre_build:
      - npm install --no-save rimraf
    build:
      html:
        - ./nx run bsb-json:docs
        - mkdir -p "$READTHEDOCS_OUTPUT/html"
        - mv packages/bsb-json/docs/_build/html/* "$READTHEDOCS_OUTPUT/html"
        - ls $READTHEDOCS_OUTPUT/html