[tool.coverage.run]
branch = true
source = [ "bsb_core" ]

[tool.coverage.report]
exclude_lines = [ "if TYPE_CHECKING:" ]
show_missing = true

[tool.pytest.ini_options]
addopts = """
 --cov
 --cov-report html:'../../coverage/packages/bsb-core/html'
 --cov-report xml:'../../coverage/packages/bsb-core/coverage.xml'
 --html='../../reports/packages/bsb-core/unittests/html/index.html'
 --junitxml='../../reports/packages/bsb-core/unittests/junit.xml'
"""

[tool.hatch.build.targets.wheel]
packages = [ "bsb_core" ]

[tool.hatch.metadata]
allow-direct-references = true

[tool.ruff]
exclude = [ ".ruff_cache", ".svn", ".tox", ".venv", "dist" ]
line-length = 88
indent-width = 4

  [tool.ruff.lint]
  select = [ "E", "F", "UP", "B", "SIM", "I" ]
  ignore = [ ]
  fixable = [ "ALL" ]
  unfixable = [ ]

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"

[project]
name = "bsb-core"
version = "1.0.3"
description = "Automatically generated by Nx."
requires-python = ">=3.9,<4"
readme = "README.md"
dependencies = [ ]

[dependency-groups]
dev = [
  "autopep8>=2.3.1",
  "ruff>=0.8.2",
  "pytest>=8.3.4",
  "pytest-sugar>=1.0.0",
  "pytest-cov>=6.0.0",
  "pytest-html>=4.1.1"
]

[build-system]
requires = [ "hatchling" ]
build-backend = "hatchling.build"
