[tool.coverage.run]
branch = true
source = [ "bsb" ]

[tool.coverage.report]
exclude_lines = [ "if TYPE_CHECKING:" ]
show_missing = true

[tool.pytest.ini_options]
addopts = """
 --cov
 --cov-report html:'../../coverage/packages/bsb-core/html'
 --cov-report xml:'../../coverage/packages/bsb-core/coverage.xml'
 --html='../../reports/packages/bsb-core/unittests/html/index.html'
 --junitxml='../../reports/packages/bsb-core/unittests/junit.xml'
"""

[tool.ruff]
exclude = [ ".ruff_cache", ".svn", ".tox", ".venv", "dist" ]
line-length = 88
indent-width = 4

  [tool.ruff.lint]
  select = [ "E", "F", "UP", "B", "SIM", "I" ]
  ignore = [ ]
  fixable = [ "ALL" ]
  unfixable = [ ]

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"

[project]
name = "bsb-core"
authors = [{ name = "Robin De Schepper", email = "robingilbert.deschepper@unipv.it" }]
readme = "README.md"
license = { file = "LICENSE" }
classifiers = ["License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)"]
requires-python = ">=3.9,<4"
dynamic = ["version", "description"]
dependencies = [
    "numpy~=1.19",
    "scipy~=1.5",
    "scikit-learn~=1.0",
    "errr~=1.2",
    "rtree~=1.0",
    "psutil~=5.8",
    "pynrrd~=1.0",
    "morphio~=3.3",
    "toml~=0.10.0",
    "requests~=2.30",
    "urllib3~=2.0",
    "appdirs~=1.4",
    "neo[nixio]",
    "tqdm~=4.50",
    "dashing-next~=0.1",
    "shortuuid~=1.0",
    "quantities~=0.15.0",
    "exceptiongroup>=1.2.0",
]

[dependency-groups]
dev = [
  "autopep8>=2.3.1",
  "ruff>=0.8.2",
  "pytest>=8.3.4",
  "pytest-sugar>=1.0.0",
  "pytest-cov>=6.0.0",
  "pytest-html>=4.1.1"
]

[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.module]
# The `bsb-core` package installs the `bsb` Python module
name = "bsb"

