[build-system]
requires = [ "flit_core >=3.2,<4" ]
build-backend = "flit_core.buildapi"

[project]
name = "bsb-core"
authors = [
  { name = "Robin De Schepper", email = "robin@alexandria.sc" },
  { name = "Dimitri Rodarie", email = "dimitri.rodarie@unipv.it" }
]
version = "5.1.1"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.9,<4"
dynamic = ["description"]
classifiers = [
  "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)"
]
dependencies = [
  "numpy~=1.19",
  "scipy~=1.5",
  "scikit-learn~=1.0",
  "errr~=1.2",
  "rtree~=1.0",
  "psutil~=5.8",
  "pynrrd~=1.0",
  "morphio~=3.3",
  "toml~=0.10.0",
  "requests~=2.30",
  "urllib3~=2.0",
  "appdirs~=1.4",
  "neo[nixio]",
  "tqdm~=4.50",
  "dashing-next~=0.1",
  "shortuuid~=1.0",
  "quantities~=0.15.0",
  "exceptiongroup>=1.2.0"
]

[project.optional-dependencies]
parallel = [
    "mpi4py~=3.0",
    "mpipool>=2.2.1,<3",
    "mpilock~=1.1"
]
test = [
    "bsb-core[parallel]",
    "bsb-arbor~=4.0; sys_platform != 'win32'",
    "bsb-hdf5~=5.0",
    "bsb-json~=4.2",
    "bsb-test",
    "coverage>=7.3",
]
docs = [
    "sphinx~=7.0",
    "furo~=2024.4",
    "sphinxemoji~=0.2.0",
    "sphinx_design~=0.5.0",
    "sphinx-copybutton~=0.5.0",
    "sphinxext-bsb~=0.2.2",
    "bsb-json~=4.2",
    "bsb-yaml~=4.0",
    "setuptools>=79.0.1",
    "sphinxext-bsb>=0.2.7"
]
dev = [
  "bsb-core[test,docs]",
  "ruff>=0.8.2",
  "snakeviz~=2.1",
]

[dependency-groups]
dev = [
  "bsb-core[dev]",
]

[tool.flit.module]
name = "bsb"

[project.entry-points."bsb.storage.engines"]
fs = "bsb.storage.fs"

[project.scripts]
bsb = "bsb.cli:handle_cli"

[project.entry-points."bsb.commands"]
commands = "bsb.cli.commands._commands"
projects = "bsb.cli.commands._projects"

[project.entry-points."bsb.options"]
verbosity = "bsb._options:verbosity"
sudo = "bsb._options:sudo"
version = "bsb._options:version"
config = "bsb._options:config"
profiling = "bsb._options:profiling"
debug_pool = "bsb._options:debug_pool"

[tool.uv.sources]
bsb-test = { path = "../bsb-test", editable = true }
bsb-hdf5 = { path = "../bsb-hdf5", editable = true }
bsb-arbor = { path = "../bsb-arbor", editable = true }
bsb-json = { path = "../bsb-json", editable = true }
bsb-yaml = { path = "../bsb-yaml", editable = true }
sphinxext-bsb = { path = "../../libs/sphinxext-bsb", editable = true }

[tool.coverage.run]
branch = true
source = [ "bsb" ]

[tool.coverage.report]
exclude_lines = [ "if TYPE_CHECKING:" ]
show_missing = true

[tool.ruff]
exclude = [ ".ruff_cache", ".svn", ".tox", ".venv", "dist" ]
line-length = 90
indent-width = 4

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-line-length = "dynamic"

[tool.ruff.lint]
select = [ "E", "F", "UP", "B", "SIM", "I" ]
ignore = [ ]
fixable = [ "ALL" ]
unfixable = [ ]
