version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.11"
    nodejs: "22"
  apt_packages:
    - libopenmpi-dev
    - openmpi-bin
  jobs:
    create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
      - cd packages/bsb && UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv sync --all-extras
    install:
      - "true"
    pre_build:
      - npm install --no-save rimraf
    build:
      html:
        - ./nx run bsb:docs

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py