[build-system]
build-backend = "setuptools.build_meta"
requires = [ "setuptools" ]

[project]
name = "bsb"
version = "6.0.0-a2"
readme = "README.md"
requires-python = ">=3.10,<4"
description = "Black-box component framework for multiscale neural modeling"
classifiers = [
  "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)"
]
dependencies = [
  "bsb-core",
  "bsb-hdf5",
  "bsb-json",
  "bsb-yaml"
]

  [[project.authors]]
  name = "Robin De Schepper"
  email = "robin@alexandria.sc"

  [[project.authors]]
  name = "Dimitri Rodarie"
  email = "dimitri.rodarie@unipv.it"

  [[project.maintainers]]
  name = "Dimitri Rodarie"
  email = "dimitri.rodarie@unipv.it"

  [project.license]
  file = "LICENSE"

  [project.optional-dependencies]
  parallel = [ "bsb-core[parallel]" ]
  neuron = [ "bsb-neuron" ]
  nest = [ "bsb-nest" ]
  arbor = [ "bsb-arbor; sys_platform != 'win32'" ]
  dev = [
  "bsb-core[dev]",
  "bsb-hdf5[dev]",
  "bsb-json[dev]",
  "bsb-yaml[dev]",
  "bsb-arbor[dev]; sys_platform != 'win32'",
  "bsb-nest[dev]",
  "bsb-neuron[dev]",
  "bsb-test[dev]",
  "gitdb>=4.0.12",
  "gitpython>=3.1.44",
  "smmap>=5.0.2"
]

  [project.urls]
  Home = "https://github.com/dbbs-lab/bsb"
  Documentation = "https://bsb.readthedocs.io/"
  "Bug Tracker" = "https://github.com/dbbs-lab/bsb/issues/"
  "Source Code" = "https://github.com/dbbs-lab/bsb/"

[dependency-groups]
dev = [ "bsb[dev]" ]

[tool.setuptools]
packages = [ ]

[tool.uv.sources.bsb-nest]
path = "../bsb-nest"
editable = true

[tool.uv.sources.bsb-neuron]
path = "../bsb-neuron"
editable = true

[tool.uv.sources.bsb-core]
path = "../bsb-core"
editable = true

[tool.uv.sources.bsb-hdf5]
path = "../bsb-hdf5"
editable = true

[tool.uv.sources.bsb-json]
path = "../bsb-json"
editable = true

[tool.uv.sources.bsb-yaml]
path = "../bsb-yaml"
editable = true

[tool.uv.sources.bsb-arbor]
path = "../bsb-arbor"
editable = true

[tool.uv.sources.bsb-test]
path = "../bsb-test"
editable = true
