[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools"]

[project]
name = "bsb"
authors = [
  { name = "Robin De Schepper", email = "robin@alexandria.sc" },
  { name = "Dimitri Rodarie", email = "dimitri.rodarie@unipv.it" }
]

maintainers = [{ name = "Dimitri Rodarie", email = "dimitri.rodarie@unipv.it" }]
version = "4.4.2"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.9,<4"
description = "Black-box component framework for multiscale neural modeling"
classifiers = [
  "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)"
]
dependencies = [
  "bsb-core",
  "bsb-hdf5",
  "bsb-arbor; sys_platform != 'win32'",
  "bsb-json",
  "bsb-yaml",
]


[project.optional-dependencies]
parallel = ["bsb-core[parallel]"]
neuron = ["bsb-neuron~=4.2.2"]
nest = ["bsb-nest~=4.3.2"]
arbor = ["bsb-arbor~=4.1.1"]
dev = [
  "bsb-core[dev]",
  "bsb-hdf5[dev]",
  "bsb-json[dev]",
  "bsb-yaml[dev]",
  "bsb-arbor[dev]",
  "bsb-test[dev]",
  "gitdb>=4.0.12",
  "gitpython>=3.1.44",
  "smmap>=5.0.2",
  "sphinxcontrib-collections @ git+https://github.com/useblocks/sphinx-collections.git@37b54c0a78e1772aabe13634ea2e2211749ac865",
]

[dependency-groups]
dev = [
  "bsb[dev]",
]

[tool.setuptools]
packages = []

[tool.uv.sources]
bsb-core = { path = "packages/bsb-core", editable = true }
bsb-hdf5 = { path = "packages/bsb-hdf5", editable = true }
bsb-json = { path = "packages/bsb-json", editable = true }
bsb-yaml = { path = "packages/bsb-yaml", editable = true }
bsb-arbor = { path = "packages/bsb-arbor", editable = true }
bsb-test = { path = "packages/bsb-test", editable = true }

[project.urls]
Home = "https://github.com/dbbs-lab/bsb"
Documentation = "https://bsb.readthedocs.io/"
"Bug Tracker" = "https://github.com/dbbs-lab/bsb/issues/"
"Source Code" = "https://github.com/dbbs-lab/bsb/"
