[build-system]
requires = [ "flit_core >=3.2,<4" ]
build-backend = "flit_core.buildapi"

[project]
name = "bsb-arbor"
authors = [
  { name = "Robin De Schepper", email = "robin@alexandria.sc" },
  { name = "Dimitri Rodarie", email = "dimitri.rodarie@unipv.it" }
]
version = "4.1.1"
dynamic = ["description"]
requires-python = ">=3.9,<3.12"
readme = 'README.md'
license = { file = "LICENSE" }
classifiers = ["License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)"]
dependencies = [
    "numpy~=1.21",
    "bsb-core~=5.0",
    "arbor~=0.10",
    "arborize[arbor]~=4.0"
]

[project.optional-dependencies]
test = [
  "bsb-core[parallel]",
  "bsb-hdf5~=5.0",
  "pytest>=8.3.4",
  "pytest-sugar>=1.0.0",
  "pytest-cov>=6.0.0",
]
dev = [
    "bsb-test[test]",
    "pre-commit~=3.5",
    "ruff>=0.8.2",
    "snakeviz~=2.1",
]

[dependency-groups]
dev = [
  "bsb-arbor[dev]",
]

[tool.flit.module]
name = "bsb_arbor"

[project.entry-points."bsb.simulation_backends"]
arbor = "bsb_arbor"

[tool.uv.sources]
bsb-core = { path = "../bsb-core", editable = true }
bsb-hdf5 = { path = "../bsb-hdf5", editable = true }
bsb-test = { path = "../bsb-test", editable = true }

[tool.coverage.run]
branch = true
source = [ "bsb_arbor" ]

[tool.coverage.report]
exclude_lines = ['if TYPE_CHECKING:']
show_missing = true

[tool.pytest.ini_options]
addopts = """
 --cov
 --cov-report html:'../../coverage/packages/bsb-arbor/html'
 --cov-report xml:'../../coverage/packages/bsb-arbor/coverage.xml'
"""

[tool.ruff]
exclude = [ ".ruff_cache", ".svn", ".tox", ".venv", "dist" ]
line-length = 88
indent-width = 4

[tool.ruff.lint]
select = [ "E", "F", "UP", "B", "SIM", "I" ]
ignore = [ ]
fixable = [ "ALL" ]
unfixable = [ ]

[[tool.uv.index]]
name = "testpypi"
url = "https://pypi.org/simple/"
publish-url = "https://pypi.org/legacy/"
