[tool.coverage.run]
branch = true
source = [ "bsb_test" ]

[tool.coverage.report]
exclude_lines = [ "if TYPE_CHECKING:" ]
show_missing = true

[tool.pytest.ini_options]
addopts = """
 --cov
 --cov-report html:'../../coverage/packages/bsb-test/html'
 --cov-report xml:'../../coverage/packages/bsb-test/coverage.xml'
 --html='../../reports/packages/bsb-test/unittests/html/index.html'
 --junitxml='../../reports/packages/bsb-test/unittests/junit.xml'
"""

[tool.ruff]
exclude = [ ".ruff_cache", ".svn", ".tox", ".venv", "dist" ]
line-length = 88
indent-width = 4

  [tool.ruff.lint]
  select = [ "E", "F", "UP", "B", "SIM", "I" ]
  ignore = [ ]
  fixable = [ "ALL" ]
  unfixable = [ ]

[tool.uv.sources]
bsb-core = { path = "../bsb-core", editable = true }

[project]
name = "bsb-test"
version = "1.0.5"
requires-python = ">=3.9,<4"
readme = "README.md"
description = """
Helpers for better and more complete tests for component developers of the BSB framework.
"""
dependencies = [
 "bsb-core",
]

[dependency-groups]
dev = [
  "autopep8>=2.3.1",
  "ruff>=0.8.2",
  "pytest>=8.3.4",
  "pytest-sugar>=1.0.0",
  "pytest-cov>=6.0.0",
  "pytest-html>=4.1.1"
]

[build-system]
requires = [ "flit_core >=3.2,<4" ]
build-backend = "flit_core.buildapi"
