name: Check branch commit

on:
  push:
    branches:
      - '**'  # matches every branch ...
      - '!main'  # ... that is not main

jobs:
  check-api:
    uses: ./.github/workflows/check-api.yml
  build:
    uses: ./.github/workflows/build.yml
  docs:
    uses: ./.github/workflows/docs.yml
  ruff:
    uses: ./.github/workflows/ruff.yml
