name: Build and test BSB

on: [ workflow_call ]

env:
  NEST_VERSION: 3.7
  NEST_FOLDER: ${{ github.workspace }}/.nx/installation/_nest_repo

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      UV_PYTHON: ${{ matrix.python-version }}
    strategy:
      matrix:
        python-version: [ "3.10", "3.11" ]
    steps:
      - uses: actions/checkout@v4

      - name: Install apt dependencies
        run: |
          sudo apt update
          # Install `libopenmpi` for MPI
          sudo apt install openmpi-bin libopenmpi-dev
          # Install `libhdf5` for `morphio`
          sudo apt install libhdf5-dev

      - name: Install nodejs
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
          \. "$HOME/.nvm/nvm.sh"
          nvm install 22

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Cache NEST
        id: cache-nest
        uses: actions/cache@v4
        with:
          path: ${{ env.NEST_FOLDER }}
          key: ${{ runner.os }}-${{ matrix.python-version }}-nest

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        id: setSHAs
        uses: nrwl/nx-set-shas@v4

      - run: ./nx affected -t test
