name: Build and test BSB

on: [workflow_call]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install apt dependencies
        run: |
          sudo apt update
          # Install `libopenmpi` for MPI
          sudo apt install openmpi-bin libopenmpi-dev
          # Install `libhdf5` for `morphio`
          sudo apt install libhdf5-dev

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - run: ./nx affected -t test
