name: Check public API

on: [workflow_call]

jobs:
  check-api:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: bsb-core affected?
      id: affected
      run: |
        echo "run_check=$(./nx show projects --affected | grep -q bsb-core && echo true || echo false)" >> $GITHUB_OUTPUT
    - name: Check public API
      if: steps.affected.outputs.run_check == 'true'
      run: ./nx run bsb-core:check-api
