name: Release

on:
  push:
    branches:
      - main

jobs:
  check-api:
    uses: ./.github/workflows/check-api.yml
  build:
    uses: ./.github/workflows/build.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  docs:
    uses: ./.github/workflows/docs.yml
  ruff:
    uses: ./.github/workflows/ruff.yml

  release:
    needs: [ruff, build, docs, check-api]
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Create Github token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.DBBS_APP_ID }}
          private-key: ${{ secrets.DBBS_APP_PRIVATE_KEY }}

      - name: Set token to env
        run: echo "GITHUB_TOKEN=${{ steps.app-token.outputs.token }}" >> $GITHUB_ENV

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Install nodejs
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
          \. "$HOME/.nvm/nvm.sh"
          nvm install --lts

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Nx Release flow
        env:
          NX_DAEMON: false
        run: |
          git config --global user.email "neurocomp_dbbs@unipv.it"
          git config --global user.name "DBBS Laboratory"
          ./nx release version --verbose
          version=`sed -n -E 's/version = "(.*)"/\1/p' packages/bsb/pyproject.toml`
          sed -i -E 's/"dateModified": "(\-?[0-9]+){3}"/"dateModified": "'$(date +%F)'"/' codemeta.json
          sed -i -E 's/"version": "(\.?[0-9]+){3}"/"version": "'$version'"/' codemeta.json
          sed -i -E 's/\/tag(s)?\/v(\.?[0-9]+){3}/\/tag\1\/v'$version'/' codemeta.json
          git add codemeta.json
          ./nx release changelog $version --verbose
          ./nx release publish --verbose
